#!/bin/bash
set -e

# Ensure required dependencies are installed before package configuration
echo "Installing required dependencies..."
sudo apt-get update
sudo apt-get install -y git, python3, python3-pip python3-flask python3-pyqt5 python3-pyqt5.qtwebengine